# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('access', models.IntegerField(default=0)),
            ],
        ),
    ]
