# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_mainview_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
