# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180424_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mainview',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keywords', to='mainApp.Keywords'),
        ),
    ]
