# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180425_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainview',
            name='access',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
