# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20181002_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainview',
            name='author',
            field=models.CharField(max_length=500),
        ),
    ]
